package lotto

enum class BaseNumber(val number: Int) {
    LOTTO_MAX_NUMBER(45),
    LOTTO_MIN_NUMBER(1),
    LOTTO_NUMBER_COUNT(6),
    THREE(3),
    FOUR(4),
    FIVE(5),
    FIVE_BONUS(7),
    SIX(6),
    LOTTO_PRICE(1000),
    THREE_WINNING_NUMBERS_COMPENSATION(5000),
    FOUR_WINNING_NUMBERS_COMPENSATION(50000),
    FIVE_WINNING_NUMBERS_COMPENSATION(1500000),
    FIVE_WINNING_NUMBERS_AND_BONUS_COMPENSATION(30000000),
    SIX_WINNING_NUMBERS_COMPENSATION(2000000000)
}