package lotto

enum class LottoPrice(val price:Int) {
    NONE(0),
    FIFTH_PLACE(FIFTH_PLACE_PRICE),
    FOURTH_PLACE(FOURTH_PLACE_PRICE),
    THIRD_PLACE(THIRD_PLACE_PRICE),
    SECOND_PLACE(SECOND_PLACE_PRICE),
    FIRST_PLACE(FIRST_PLACE_PRICE)
}