package lotto.domain

import lotto.utils.*

enum class LottoRank(
    val message: String,
    val reward: Int
) {
    NO_LUCK(LOTTO_NO_LUCK_MESSAGE, NO_LUCK_REWARD),
    FIRST(LOTTO_FIRST_RANK_MESSAGE, FIRST_REWARD),
    SECOND(LOTTO_SECOND_RANK_MESSAGE, SECOND_REWARD),
    THIRD(LOTTO_THIRD_RANK_MESSAGE, THIRD_REWARD),
    FOURTH(LOTTO_FOURTH_RANK_MESSAGE, FOURTH_REWARD),
    FIFTH(LOTTO_FIFTH_RANK_MESSAGE, FIFTH_REWARD);
}